### ISSUE TITLE
@とスペースの補完

### ISSUE THREAD

**Issue by ma-tw** [kkbpc/twitter-for-cli#1]
メンションするユーザー名のところのアットマークとスペースがない場合補完してくれる機能を追加しました。(GitHub使ったことないのでissuesの書き方間違ってたらすみません)

    if usr_id == "":
        tweet_text = text
    else:
        if usr_id[0] == "@":
            pass
        else:
            usr_id = "@" + usr_id
        
        if usr_id[-1] == " ":
            tweet_text = usr_id + text
        else:
            tweet_text = usr_id + " " + text

**Comment by kkbpc** [comment]
提案ありがとう
近いうちに実装します！
